/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.addmoto.view;

import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import project.addmoto.controller.InventoryController;
import project.addmoto.database.Query;
/**
 *
 * @author Kevin
 */
public class AddItem extends javax.swing.JPanel {

    private Query query;
    private JFrame parent;
    /**
     * Creates new form AddItem
     */
    public AddItem() {
     
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNewProductLabel = new javax.swing.JLabel();
        iSupplierLabel = new javax.swing.JLabel();
        iSupplierList = new javax.swing.JComboBox<>();
        iProductLineLabel = new javax.swing.JLabel();
        iProductLineList = new javax.swing.JComboBox<>();
        iSupplierCodeLabel = new javax.swing.JLabel();
        iSupplierCodeText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        iUnitPriceLabel = new javax.swing.JLabel();
        iUnitPriceText = new javax.swing.JTextField();
        iQtyText = new javax.swing.JTextField();
        iQtyLabel = new javax.swing.JLabel();
        iDescriptionText = new javax.swing.JTextField();
        iDescriptionLabel = new javax.swing.JLabel();
        iCharacteristicsText = new javax.swing.JTextField();
        iCharacteristicsLabel = new javax.swing.JLabel();
        iSellingPriceText = new javax.swing.JTextField();
        iSellingPriceLabel = new javax.swing.JLabel();
        iThresholdText = new javax.swing.JTextField();
        iThresholdLabel = new javax.swing.JLabel();
        iModelText = new javax.swing.JTextField();
        iModelLabel = new javax.swing.JLabel();

        jNewProductLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jNewProductLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/addmoto/icons/inventory_logo.png"))); // NOI18N
        jNewProductLabel.setText("Add New Product");

        iSupplierLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iSupplierLabel.setText("Supplier:");

        iSupplierList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        iSupplierList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iSupplierListActionPerformed(evt);
            }
        });

        iProductLineLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iProductLineLabel.setText("Product Line: ");

        iProductLineList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        iProductLineList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iProductLineListActionPerformed(evt);
            }
        });

        iSupplierCodeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iSupplierCodeLabel.setText("Supplier Code:");

        iUnitPriceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iUnitPriceLabel.setText("Unit Price:");

        iQtyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iQtyLabel.setText("Qty on Hand:");

        iDescriptionLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iDescriptionLabel.setText("Description:");

        iCharacteristicsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iCharacteristicsLabel.setText("Characteristics:");

        iSellingPriceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iSellingPriceLabel.setText("Selling Price:");

        iThresholdLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iThresholdLabel.setText("Threshold:");

        iModelLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iModelLabel.setText("Model:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(iSupplierLabel)
                            .addGap(18, 18, 18)
                            .addComponent(iSupplierList, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(iProductLineLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(iProductLineList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jNewProductLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(iSupplierCodeLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(iSupplierCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(iUnitPriceLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(iUnitPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(iSellingPriceLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(iSellingPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(iDescriptionLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(iDescriptionText))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(iCharacteristicsLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(iCharacteristicsText))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(iQtyLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(iQtyText, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(iThresholdLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(iThresholdText, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(iModelLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(iModelText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jNewProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iSupplierLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iSupplierList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iProductLineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iProductLineList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iSupplierCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iSupplierCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iUnitPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iUnitPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iSellingPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iSellingPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iQtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iQtyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iThresholdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iThresholdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(iCharacteristicsText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iModelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iModelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(iCharacteristicsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iDescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iSupplierListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iSupplierListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iSupplierListActionPerformed

    private void iProductLineListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iProductLineListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iProductLineListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iCharacteristicsLabel;
    private javax.swing.JTextField iCharacteristicsText;
    private javax.swing.JLabel iDescriptionLabel;
    private javax.swing.JTextField iDescriptionText;
    private javax.swing.JLabel iModelLabel;
    private javax.swing.JTextField iModelText;
    private javax.swing.JLabel iProductLineLabel;
    private javax.swing.JComboBox<String> iProductLineList;
    private javax.swing.JLabel iQtyLabel;
    private javax.swing.JTextField iQtyText;
    private javax.swing.JLabel iSellingPriceLabel;
    private javax.swing.JTextField iSellingPriceText;
    private javax.swing.JLabel iSupplierCodeLabel;
    private javax.swing.JTextField iSupplierCodeText;
    private javax.swing.JLabel iSupplierLabel;
    private javax.swing.JComboBox<String> iSupplierList;
    private javax.swing.JLabel iThresholdLabel;
    private javax.swing.JTextField iThresholdText;
    private javax.swing.JLabel iUnitPriceLabel;
    private javax.swing.JTextField iUnitPriceText;
    private javax.swing.JLabel jNewProductLabel;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getiProductLineList() {
        return iProductLineList;
    }

    public JComboBox<String> getiSupplierList() {
        return iSupplierList;
    }

    public JTextField getiCharacteristicsText() {
        return iCharacteristicsText;
    }

    public JTextField getiDescriptionText() {
        return iDescriptionText;
    }

    public JTextField getiModelText() {
        return iModelText;
    }

    public JTextField getiQtyText() {
        return iQtyText;
    }

    public JTextField getiSellingPriceText() {
        return iSellingPriceText;
    }

    public JTextField getiSupplierCodeText() {
        return iSupplierCodeText;
    }

    public JTextField getiThresholdText() {
        return iThresholdText;
    }

    public JTextField getiUnitPriceText() {
        return iUnitPriceText;
    }   
}