package project.addmoto.view;

import javax.swing.JOptionPane;
import project.addmoto.database.Query;

/**
 *
 * @author Kim Howel delos Reyes
 */
public class UI_Login extends javax.swing.JFrame {

    /**
     * Creates new form UI_Login
     */
    public UI_Login() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    
    /*
    These methods get the value from views
    */
    private String getUsername() {
        return UILogin_jTextField_username.getText();
    }
    
    private String getPassword() {
        return new String(UILogin_jPasswordField_password.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UILogin_jLabel_username = new javax.swing.JLabel();
        UILogin_jLabel_password = new javax.swing.JLabel();
        UILogin_jTextField_username = new javax.swing.JTextField();
        UILogin_jPasswordField_password = new javax.swing.JPasswordField();
        UILogin_jButton_createNew = new javax.swing.JButton();
        UILogin_jButton_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD Moto - Motorcycle Parts and Accessories");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        UILogin_jLabel_username.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        UILogin_jLabel_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UILogin_jLabel_username.setText("Username:");

        UILogin_jLabel_password.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        UILogin_jLabel_password.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UILogin_jLabel_password.setText("Password:");

        UILogin_jTextField_username.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        UILogin_jTextField_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        UILogin_jPasswordField_password.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        UILogin_jPasswordField_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        UILogin_jButton_createNew.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        UILogin_jButton_createNew.setText("Create");
        UILogin_jButton_createNew.setToolTipText("");

        UILogin_jButton_login.setFont(new java.awt.Font("Century Gothic", 0, 22)); // NOI18N
        UILogin_jButton_login.setText("Login");
        UILogin_jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UILogin_jButton_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UILogin_jLabel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UILogin_jLabel_username, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UILogin_jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UILogin_jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(UILogin_jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UILogin_jButton_createNew, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UILogin_jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UILogin_jLabel_username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UILogin_jLabel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UILogin_jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UILogin_jButton_createNew, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UILogin_jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UILogin_jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UILogin_jButton_loginActionPerformed
        String username = getUsername();
        String password = getPassword();
        int returnedValue = new Query().getSellerAccount(username, password);
        if(returnedValue == 1) {
            JOptionPane.showMessageDialog(UI_Login.this, "Login Successfully!");
        } else {
            JOptionPane.showMessageDialog(UI_Login.this, "Login Not Successful!");
        }
    }//GEN-LAST:event_UILogin_jButton_loginActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UILogin_jButton_createNew;
    private javax.swing.JButton UILogin_jButton_login;
    private javax.swing.JLabel UILogin_jLabel_password;
    private javax.swing.JLabel UILogin_jLabel_username;
    private javax.swing.JPasswordField UILogin_jPasswordField_password;
    private javax.swing.JTextField UILogin_jTextField_username;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
